# Gitleaks Configuration for PingBuoy
# https://github.com/gitleaks/gitleaks

title = "PingBuoy Secrets Detection Configuration"

[extend]
# Use the default gitleaks rules as a base
useDefault = true

[[rules]]
id = "stripe-secret-key"
description = "Stripe Secret Key"
regex = '''sk_live_[0-9a-zA-Z]{24}'''
keywords = ["sk_live_"]

[[rules]]
id = "stripe-restricted-key"
description = "Stripe Restricted Key"
regex = '''rk_live_[0-9a-zA-Z]{24}'''
keywords = ["rk_live_"]

[[rules]]
id = "stripe-publishable-key"
description = "Stripe Publishable Key (usually safe but worth monitoring)"
regex = '''pk_live_[0-9a-zA-Z]{24}'''
keywords = ["pk_live_"]

[[rules]]
id = "supabase-anon-key"
description = "Supabase Anonymous Key (usually safe for client-side but worth monitoring)"
regex = '''eyJ[A-Za-z0-9_/+-]*\.eyJ[A-Za-z0-9_/+-]*\.[A-Za-z0-9_/+-]*'''
keywords = ["supabase", "anon"]

[[rules]]
id = "supabase-service-key"
description = "Supabase Service Role Key (CRITICAL)"
regex = '''eyJ[A-Za-z0-9_/+-]*\.eyJ[A-Za-z0-9_/+-]*\.[A-Za-z0-9_/+-]*'''
keywords = ["supabase", "service_role", "service-role"]

[[rules]]
id = "nextauth-secret"
description = "NextAuth Secret"
regex = '''[a-zA-Z0-9+/]{32,}'''
keywords = ["NEXTAUTH_SECRET", "nextauth"]

[[rules]]
id = "redis-password"
description = "Redis Password"
regex = '''redis://[^:]*:([^@]+)@'''
keywords = ["redis://"]

[[rules]]
id = "smtp-password"
description = "SMTP Password"
regex = '''smtp.*password.*[=:]\s*["\']?([^"\'\s]+)'''
keywords = ["SMTP_PASS", "smtp_password"]

[[rules]]
id = "webhook-secret"
description = "Webhook Secret"
regex = '''whsec_[a-zA-Z0-9]{32,64}'''
keywords = ["whsec_"]

[[rules]]
id = "upstash-redis-url"
description = "Upstash Redis URL"
regex = '''https://[a-z0-9-]+\.upstash\.io'''
keywords = ["upstash.io"]

[[rules]]
id = "vercel-token"
description = "Vercel Token"
regex = '''[a-zA-Z0-9]{24}'''
keywords = ["VERCEL_TOKEN", "vercel_token"]

[[rules]]
id = "openai-api-key"
description = "OpenAI API Key"
regex = '''sk-[a-zA-Z0-9]{48}'''
keywords = ["sk-", "openai"]

[[rules]]
id = "anthropic-api-key"
description = "Anthropic API Key"
regex = '''sk-ant-[a-zA-Z0-9\-_]{95}'''
keywords = ["sk-ant-", "anthropic"]

# Custom rules for common secrets patterns
[[rules]]
id = "generic-api-key"
description = "Generic API Key Pattern"
regex = '''(?i)(api[_-]?key|apikey|secret[_-]?key|access[_-]?token)[_-]*[=:]\s*["\']?([a-zA-Z0-9_\-]{16,})'''
keywords = ["api_key", "apikey", "secret_key", "access_token"]

[[rules]]
id = "database-url"
description = "Database Connection URL"
regex = '''(?i)(postgres|mysql|mongodb)://[^:]*:[^@]*@[^/]*'''
keywords = ["postgres://", "mysql://", "mongodb://"]

[[rules]]
id = "private-key"
description = "Private Key"
regex = '''-----BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY-----'''
keywords = ["PRIVATE KEY"]

[[rules]]
id = "jwt-secret"
description = "JWT Secret"
regex = '''(?i)jwt[_-]?secret[_-]*[=:]\s*["\']?([a-zA-Z0-9_\-+/]{32,})'''
keywords = ["jwt_secret", "jwt-secret"]

# Allowlist for known safe patterns
[allowlist]
description = "Allowlist for safe patterns and test data"
regexes = [
    # Test API keys that are clearly fake
    '''test_[a-zA-Z0-9]{24}''',
    '''fake_[a-zA-Z0-9]{24}''',
    '''mock_[a-zA-Z0-9]{24}''',
    '''example_[a-zA-Z0-9]{24}''',
    '''demo_[a-zA-Z0-9]{24}''',

    # Placeholder values
    '''your_api_key_here''',
    '''your_secret_here''',
    '''replace_with_your_key''',
    '''<your-.*>''',
    '''\{\{.*\}\}''',
    '''\$\{.*\}''',

    # Common test strings
    '''sk_test_[a-zA-Z0-9]{24}''',
    '''pk_test_[a-zA-Z0-9]{24}''',
    '''acct_1234567890''',

    # Documentation examples
    '''sk_live_51H[a-zA-Z0-9]{24}''', # Common Stripe docs example
    '''pk_live_51H[a-zA-Z0-9]{24}''',
]

paths = [
    # Ignore build and dependency directories
    '''node_modules/''',
    '''.next/''',
    '''dist/''',
    '''build/''',
    '''coverage/''',

    # Ignore log files
    '''*.log''',
    '''logs/''',

    # Ignore common config files that might have false positives
    '''package-lock.json''',
    '''yarn.lock''',
    '''pnpm-lock.yaml''',

    # Ignore documentation that might contain example keys
    '''README.md''',
    '''CHANGELOG.md''',
    '''docs/''',
]

commits = [
    # Example: allowlist specific commits if they contained test data
    # "commit-hash-here",
]

# Stop scanning at these paths (performance optimization)
[allowlist.stopwords]
stopwords = [
    "example",
    "test",
    "fake",
    "mock",
    "demo",
    "placeholder",
    "sample",
    "template"
]