name: Uptime Monitoring

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  uptime-check:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Uptime Monitoring
        run: |
          curl -X POST "${{ secrets.APP_URL }}/api/cron/uptime" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            --fail \
            --max-time 300
        env:
          APP_URL: ${{ secrets.APP_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}

      - name: Log completion
        run: echo "Uptime monitoring check completed at $(date)"