name: Uptime Monitoring

on:
  schedule:
    # Run every 1 minute for Pro users, every 5 minutes for Free users
    - cron: '* * * * *'  # Every minute
    - cron: '*/5 * * * *' # Every 5 minutes
  workflow_dispatch: # Allow manual triggering

jobs:
  pro-uptime-check:
    runs-on: ubuntu-latest
    if: github.event.schedule == '* * * * *'  # Every minute
    steps:
      - name: Trigger Pro Uptime Monitoring
        run: |
          curl -X POST "${{ secrets.APP_URL }}/api/cron/uptime" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            -d '{"plan": "pro"}' \
            --fail \
            --max-time 300
        env:
          APP_URL: ${{ secrets.APP_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}

      - name: Log Pro completion
        run: echo "Pro uptime monitoring check completed at $(date)"

  free-uptime-check:
    runs-on: ubuntu-latest
    if: github.event.schedule == '*/5 * * * *'  # Every 5 minutes
    steps:
      - name: Trigger Free Uptime Monitoring
        run: |
          curl -X POST "${{ secrets.APP_URL }}/api/cron/uptime" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            -d '{"plan": "free"}' \
            --fail \
            --max-time 300
        env:
          APP_URL: ${{ secrets.APP_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}

      - name: Log Free completion
        run: echo "Free uptime monitoring check completed at $(date)"